name: imagesearchgallery
description: search for images and save them to view in a gallery

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  fluter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  freezed_annotation: ^0.15.0
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  dio: ^4.0.1
  dio_cache_interceptor: ^3.2.2
  transparent_image: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.4.1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.7
  path: ^1.8.0
  permission_handler: ^8.3.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^0.15.0+1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/secret.txt
